{
 "title": "Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Juggler and orchestrator RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (rate(flask_http_request_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed messages by bot per minute",
   "type": "timeseries",
   "description": "Number of processed messages by bot per minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(processed_messages_total[1m])) by (job) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM used bytes",
   "type": "timeseries",
   "description": "JVM used bytes in bot module",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (area) (jvm_memory_used_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id) (jvm_memory_used_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC allocations speed",
   "type": "timeseries",
   "description": "JVM Garbage Collector allocations speed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (rate(jvm_gc_memory_allocated_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}