package com.github.nad777.bot.core;

public enum State {
    WAITING_FOR_COMMAND,
    WAITING_FOR_TASK_TO_SUBMIT,
    WAITING_FOR_TASK_FILE,
    WAITING_FOR_TASK_INFO,
    WAITING_FOR_MASTER_SOLUTION
}
